sudo: required
dist: trusty
language: csharp
mono: none
dotnet: 1.0.0-preview2-003121

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:  
 - command -v nvm
 - nvm install 6.10
 - nvm use 6.10
 - node --version
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

before_script:
- npm install -g karma-cli
- cd ./SpaApp/SpaApp/
- npm install
- npm run build

script: karma start karma.conf.js --single-run
